### ISSUE TITLE
.env does not exist.

### ISSUE THREAD

**Issue by tingtingLiuLiu** [gwthomas/Safe-MBPO#1]
Hi ,I would like to ask a question. I run main.py and have a problem.
What should I do? Looking forward to your reply, grateful !!!
Traceback (most recent call last):
  File "F:/Safe-MBPO-main/Safe-MBPO-main/main.py", line 12, in <module>
    from src.shared import get_env
  File "F:\Safe-MBPO-main\Safe-MBPO-main\src\shared.py", line 5, in <module>
    from .sampling import SampleBuffer
  File "F:\Safe-MBPO-main\Safe-MBPO-main\src\sampling.py", line 6, in <module>
    from .env.util import env_dims, isdiscrete, get_max_episode_steps
ModuleNotFoundError: No module named 'src.env'

**Comment by que10** [comment]
I have met the same question with you. I solved this by clicking the 'Force' in the third line and download the env folder in it. However, I also missed some files after doing that.

**Comment by tingtingLiuLiu** [comment]
Thanks ，I also solved this problem.But still encountered some problems.
/home/ltt/anaconda3/envs/recovery/bin/python /home/ltt/Downloads/Safe-MBPO-main/main.py -c config/ant.json
/home/ltt/anaconda3/envs/recovery/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "/home/ltt/Downloads/Safe-MBPO-main/main.py", line 12, in <module>
    from src.shared import get_env
  File "/home/ltt/Downloads/Safe-MBPO-main/src/shared.py", line 5, in <module>
    from .sampling import SampleBuffer
  File "/home/ltt/Downloads/Safe-MBPO-main/src/sampling.py", line 6, in <module>
    from .env.util import env_dims, isdiscrete, get_max_episode_steps
  File "/home/ltt/Downloads/Safe-MBPO-main/src/env/util.py", line 9, in <module>
    from .torch_wrapper import TorchWrapper
  File "/home/ltt/Downloads/Safe-MBPO-main/src/env/torch_wrapper.py", line 3, in <module>
    from force.torch_util import torchify, numpyify
  File "/home/ltt/Downloads/Safe-MBPO-main/force/__init__.py", line 9, in <module>
    MACHINE_VARIABLES = __load()
  File "/home/ltt/Downloads/Safe-MBPO-main/force/__init__.py", line 6, in __load
    assert path.is_file()
AssertionError
What does the machine.json file refer to?
this is my‘s ’/home/ltt/Downloads/Safe-MBPO-main/force/machine.json

**Comment by SJ9VRF** [comment]
> I have met the same question with you. I solved this by clicking the 'Force' in the third line and download the env folder in it. However, I also missed some files after doing that.

We need tasks files ()  from env file, which are not available in force/env. It's not a solution.

Following files are missing in force/env file:

    from .env.hopper_no_bonus import HopperNoBonusEnv
    from .env.cheetah_no_flip import CheetahNoFlipEnv
    from .env.ant_no_bonus import AntNoBonusEnv
    from .env.humanoid_no_bonus import HumanoidNoBonusEnv

**Comment by SJ9VRF** [comment]
The issue is solved. /env/ folder is added.

**Comment by SJ9VRF** [comment]
> Hi ,I would like to ask a question. I run main.py and have a problem.
> What should I do? Looking forward to your reply, grateful !!!
> Traceback (most recent call last):
> File "F:/Safe-MBPO-main/Safe-MBPO-main/main.py", line 12, in 
> from src.shared import get_env
> File "F:\Safe-MBPO-main\Safe-MBPO-main\src\shared.py", line 5, in 
> from .sampling import SampleBuffer
> File "F:\Safe-MBPO-main\Safe-MBPO-main\src\sampling.py", line 6, in 
> from .env.util import env_dims, isdiscrete, get_max_episode_steps
> ModuleNotFoundError: No module named 'src.env'



> I have met the same question with you. I solved this by clicking the 'Force' in the third line and download the env folder in it. However, I also missed some files after doing that.

It's not the solution, force/env/ is a different folder

**Comment by Maya199x** [comment]
Hey guys I can't get the example to run. I wanted to ask what systems are ### **you** using? I've tried on a VM Ubuntu 20.04 and on an mac arm m1 but to no avail. At the end of the day it always fails because of mujoco. Maybe I am setting it up wrong, I don't know
